### ISSUE TITLE
Add Landing Page

### ISSUE THREAD

**Issue by sumitkr2000** [KiranAminPanjwani/Work-Flash#15]
### 🎇 Description

Hey @KiranAminPanjwani I want to add a landing page to your website. Please assign me this issue.  Thank you!

### 📷 Screenshots

![Screenshot (348)](https://user-images.githubusercontent.com/100675296/193888652-e6b10150-ea0b-48f2-809a-b66c22d76b9f.png)

**Comment by KiranAminPanjwani** [comment]
Yes, sure you can! Please create a PR🤩
