### ISSUE TITLE
Contributor label in the readme file

### ISSUE THREAD

**Issue by Hariom8799** [KiranAminPanjwani/Work-Flash#22]
### 🎇 Description

You can add the contributor label to the readme to attract more contributor

### 📷 Screenshots

![194721540-e2c06f16-cdcf-4d0d-8f58-964f96d5fd95](https://user-images.githubusercontent.com/76242202/194736074-1c6bef46-733c-4649-a1ba-e2044c4b4fd0.png)

**Comment by KiranAminPanjwani** [comment]
I will add it. Please try to find other bugs/issues if possible.
